#!/bin/sh
OUTPUT="README.md"
images="./previews"

i=0
echo "# Rainbou Colors" > $OUTPUT
for svg in `find $images -maxdepth 1 -mindepth 1 -type f| sort`; do
  image=`basename $svg`
  echo "## $image" >> $OUTPUT
  echo "![$image](./previews/$image)  " >> $OUTPUT
done
