#!/bin/sh

b=$(tput bold)
cr=$(tput setaf 1)
n=$(tput sgr0)

header="Please select a color scheme"

swap_dialog() {
  NEW_THEME=$(rainbou ls s | fzf --header="$header")
  if [ -z $NEW_THEME ]; then
    echo "Aborted!"
  else
    rainbou ${NEW_THEME} xres >~/.xres/colors/active
    rainbou ${NEW_THEME} 2bwm >~/.xres/2bwm
    xrdb ~/.Xresources
    rainbou ${NEW_THEME} kitty >~/dotfiles/kitty/.config/kitty/colors.conf
    kitty @ set-colors -a "~/dotfiles/kitty/.config/kitty/colors.conf"
    rainbou ${NEW_THEME} alacritty >~/dotfiles/alacritty/.config/alacritty/alacritty.yml
    rainbou ${NEW_THEME} linux_tty >~/dotfiles/zsh/.zsh/zsh_tty
    rainbou ${NEW_THEME} gedit >~/dotfiles/gedit/.local/share/gedit/styles/${NEW_THEME}.xml
    rainbou ${NEW_THEME} polybar >~/dotfiles/polybar/.config/polybar/colors.ini
    rainbou ${NEW_THEME} rofi_applets >~/dotfiles/rofi/.config/rofi/applets/colors.rasi
    rainbou ${NEW_THEME} rofi_launchers >~/dotfiles/rofi/.config/rofi/launchers/colors.rasi
    rainbou ${NEW_THEME} ulauncher >~/dotfiles/ulauncher/.config/ulauncher/user-themes/rainbou/theme.css
    mkdir -p ~/dotfiles/oomox/.config/oomox/colors/${NEW_THEME}
    rainbou ${NEW_THEME} oomox >~/dotfiles/oomox/.config/oomox/colors/${NEW_THEME}/${NEW_THEME}
    rainbou ${NEW_THEME} herbstluftwm >~/dotfiles/herbstluftwm/.config/herbstluftwm/theme/rainbou.sh
    rainbou ${NEW_THEME} jgmenu >~/dotfiles/jgmenu/.config/jgmenu/jgmenurc
    rainbou ${NEW_THEME} plank >~/dotfiles/plank/.local/share/plank/themes/rainbou/dock.theme
    rainbou ${NEW_THEME} deadd >~/dotfiles/deadd/.config/deadd/deadd.css
    rainbou ${NEW_THEME} dunst >~/dotfiles/dunst/.config/dunst/dunstrc
    rainbou ${NEW_THEME} gtk >~/.themes/rainbou/gtk-3.0/gtk.css
    rainbou ${NEW_THEME} gtkrc >~/.themes/rainbou/gtk-2.0/gtkrc
    rainbou ${NEW_THEME} zathura >~/dotfiles/zathura/.config/zathura/zathurarc
    rainbou ${NEW_THEME} imv >~/dotfiles/imv/.config/imv/config
    rainbou ${NEW_THEME} openbox >~/.themes/rainbou/openbox-3/themerc
    #openbox --reconfigure
    rainbou ${NEW_THEME} qt5ct >~/.config/qt5ct/colors/rainbou.conf
    rainbou ${NEW_THEME} kvantum >~/.config/Kvantum/Rainbou/Rainbou.kvconfig
    #rainbou ${NEW_THEME} telegram > ~/Rainbou.tdesktop-theme
    rainbou ${NEW_THEME} escsequences >/tmp/escsequences
    sh /tmp/escsequences
    #rainbou ${NEW_THEME} gnome-terminal >/tmp/gnome-terminal-theme
    #sh /tmp/gnome-terminal-theme
    #rainbou ${NEW_THEME} konsole >~/.local/share/konsole/rainbou.colorscheme
    #rainbou ${NEW_THEME} wallpaper-octagon > ~/Resimler/Wallpapers/Rainbou/${NEW_THEME}-octagon.svg
    #rainbou ${NEW_THEME} wallpaper-blockwave > ~/Resimler/Wallpapers/Rainbou/${NEW_THEME}-blockwave.svg
    #rainbou ${NEW_THEME} wallpaper-diamonds > ~/Resimler/Wallpapers/Rainbou/${NEW_THEME}-diamonds.svg
    #rainbou ${NEW_THEME} wallpaper-tortoise > ~/Resimler/Wallpapers/Rainbou/${NEW_THEME}-tortoise.svg
    rainbou ${NEW_THEME} firefox-dark > ~/.mozilla/firefox/wmhune9w.default-release/chrome/firefox-gnome-theme/theme/colors/dark-rainbou.css
    rainbou ${NEW_THEME} userContent.css > ~/.mozilla/firefox/wmhune9w.default-release/chrome/userContent.css
    echo "Colorscheme ${b}${cr}${NEW_THEME}${n} is set!"
  fi
}

if hash fzf 2>/dev/null; then
  swap_dialog
else
  echo "Please install ${b}${cr}fzf${n} to use this script."
fi
