#!/bin/bash
echo "Colorscheme Name:"
read  colorschemename
echo "Colorscheme Author:"
read author

file="$1"
file_name="$(echo $colorschemename | tr '[:upper:]' '[:lower:]')"

colors () {
  BG=$(grep "*background:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  FG=$(grep "*foreground:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  CR=$(grep "*cursorColor:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C0=$(grep "*color0:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C1=$(grep "*color1:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C2=$(grep "*color2:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C3=$(grep "*color3:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C4=$(grep "*color4:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C5=$(grep "*color5:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C6=$(grep "*color6:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C7=$(grep "*color7:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C8=$(grep "*color8:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C9=$(grep "*color9:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C10=$(grep "*color10:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C11=$(grep "*color11:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C12=$(grep "*color12:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C13=$(grep "*color13:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C14=$(grep "*color14:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  C15=$(grep "*color15:" $file | awk '$1==$1{print $2}' | sed -e "s/\#//")
  pos="-1"
}

yaml() {
  colors

  printf "metadata:\n"
  printf "  name: $colorschemename\n"
  printf "  author: $author\n"
  printf "colors:\n"
  printf "  bg: \"$BG\"\n"
  printf "  fg: \"$FG\"\n"
  printf "  cr: \"$CR\"\n\n"

  printf "  00: \"$C0\"\n"
  printf "  08: \"$C8\"\n\n"

  printf "  01: \"$C1\"\n"
  printf "  09: \"$C9\"\n\n"

  printf "  02: \"$C2\"\n"
  printf "  10: \"$C10\"\n\n"

  printf "  03: \"$C3\"\n"
  printf "  11: \"$C11\"\n\n"

  printf "  04: \"$C4\"\n"
  printf "  12: \"$C12\"\n\n"

  printf "  05: \"$C5\"\n"
  printf "  13: \"$C13\"\n\n"

  printf "  06: \"$C6\"\n"
  printf "  14: \"$C14\"\n\n"

  printf "  07: \"$C7\"\n"
  printf "  15: \"$C15\""
}

yaml > ${file_name}.yaml
