#!/bin/sh
profile=$(gsettings get org.gnome.Terminal.ProfilesList default | sed s/\'//g)

dconf write /org/gnome/terminal/legacy/profiles:/:$profile/background-color "'#{{index .ColorMap "bg" "hex"}}'"
dconf write /org/gnome/terminal/legacy/profiles:/:$profile/foreground-color "'#{{index .ColorMap "fg" "hex"}}'"
dconf write /org/gnome/terminal/legacy/profiles:/:$profile/cursor-background-color "'#{{index .ColorMap "cr" "hex"}}'"
dconf write /org/gnome/terminal/legacy/profiles:/:$profile/cursor-foreground-color "'#{{index .ColorMap "fg" "hex"}}'"
dconf write /org/gnome/terminal/legacy/profiles:/:$profile/palette "['#{{index .ColorMap "00" "hex"}}', '#{{index .ColorMap "01" "hex"}}', '#{{index .ColorMap "02" "hex"}}', '#{{index .ColorMap "03" "hex"}}', '#{{index .ColorMap "04" "hex"}}', '#{{index .ColorMap "05" "hex"}}', '#{{index .ColorMap "06" "hex"}}', '#{{index .ColorMap "07" "hex"}}', '#{{index .ColorMap "08" "hex"}}', '#{{index .ColorMap "09" "hex"}}', '#{{index .ColorMap "10" "hex"}}', '#{{index .ColorMap "11" "hex"}}', '#{{index .ColorMap "12" "hex"}}', '#{{index .ColorMap "13" "hex"}}', '#{{index .ColorMap "14" "hex"}}', '#{{index .ColorMap "15" "hex"}}']"
